CULTUREBANK_FIELDS = [
    "cultural group",
    "context",
    "goal",
    "relation",
    "actor",
    "recipient",
    "actor's behavior",
    "recipient's behavior",
    "other descriptions",
    "topic",
    "norm",
]

EVAL_FIELDS = [
    "cultural group",
    "context",
    "actor",
    "recipient",
    "relation",
    "actor's behavior",
    "goal",
    "recipient's behavior",
    "other descriptions",
]

DESC_FIELDS = [
    "cultural group",
    "context",
    "actor",
    "recipient",
    "relation",
    "actor's behavior",
    "goal",
    "recipient's behavior",
    "other descriptions",
    "norm",
]

SUMMARIZER_FIELDS = [
    "cultural group",
    "context",
    "actor",
    "recipient",
    "relation",
    "actor's behavior",
    "goal",
    "recipient's behavior",
    "other descriptions",
]

CLUSTERING_STAT_FIELDS = [
    "cluster_id",
    "cluster_size",
    "raw_sample_vids",
    "raw_samples",
    "raw_sample_times",
    "raw_sample_norms",
]
CULTURAL_TOPICS = [
    "Food and Dining",
    "Drinking and Alcohol",
    "Cultural Exchange",
    "Communication and Language",
    "Consumer Behavior",
    "Social Norms and Etiquette",
    "Health and Hygiene",
    "Family Dynamics",
    "Household and Daily Life",
    "Social Interactions",
    "Relationships and Marriage",
    "Lifestyles",
    "Workplace",
    "Work-Life Balance",
    "Environmental Adaptation and Sustainability",
    "Cultural and Environmental Appreciation",
    "Community and Identity",
    "Family Traditions and Heritage",
    "Cultural Traditions and Festivals",
    "Religious Practices",
    "Beauty and Fashion",
    "Dress Codes",
    "Safety and Security",
    "Education and Technology",
    "Entertainment and Leisure",
    "Housing and Interior Design",
    "Transportation",
    "Social Infrastructure",
    "Time Management and Punctuality",
    "Pet and Animal Care",
    "Migration and Cultural Adaptation",
    "Finance and Economy",
    "Humor and Storytelling",
    "Sports and Recreation",
    "Travelling",
    "Miscellaneous",
]
